CREATE TABLE DIVISION(
   DIVISION VARCHAR(13) NOT NULL PRIMARY KEY
);
INSERT INTO DIVISION(DIVISION) VALUES ('NONE');
INSERT INTO DIVISION(DIVISION) VALUES ('ALABAMA');
INSERT INTO DIVISION(DIVISION) VALUES ('DEARBORN');
INSERT INTO DIVISION(DIVISION) VALUES ('DETROIT CSAO');
INSERT INTO DIVISION(DIVISION) VALUES ('GEORGIA');
INSERT INTO DIVISION(DIVISION) VALUES ('HARRISBURG');
INSERT INTO DIVISION(DIVISION) VALUES ('ILLINOIS');
INSERT INTO DIVISION(DIVISION) VALUES ('LAKE');
INSERT INTO DIVISION(DIVISION) VALUES ('N JERSEY CSAO');
INSERT INTO DIVISION(DIVISION) VALUES ('PIEDMONT');
INSERT INTO DIVISION(DIVISION) VALUES ('PITTSBURGH');
INSERT INTO DIVISION(DIVISION) VALUES ('POCAHONTAS');
INSERT INTO DIVISION(DIVISION) VALUES ('S JERSEY CSAO');
INSERT INTO DIVISION(DIVISION) VALUES ('SYSTEM');